version: "3.8"

services:
  core:
    container_name: core_service
    build:
      context: .
      dockerfile: Dockerfile
    #restart: always
    tty: true
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - "./logs:/app/logs"
    depends_on:
      - db
    networks:
      - log-service

  db:
    container_name: service_db
    image: "mysql:latest"
    ports:
      - "33060:3306"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MYSQL_DATABASE: '${DATABASE}'
      MYSQL_ROOT_PASSWORD: '${ROOT_PASSWORD}'
      MYSQL_USER: '${USERNAME}'
      MYSQL_PASSWORD: '${PASSWORD}'
    networks:
      - log-service

networks:
  log-service: